
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Mar 05 01:11:22 CET 2016
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STR2INT = 11;
  public static final int AND = 19;
  public static final int MENOS = 16;
  public static final int IDENT = 33;
  public static final int TESIS = 24;
  public static final int ELSE = 6;
  public static final int OR = 20;
  public static final int ENDIF = 7;
  public static final int THEN = 5;
  public static final int WHILE = 8;
  public static final int CIERRALLAVE = 27;
  public static final int PAREN = 23;
  public static final int NOT = 13;
  public static final int MAYORQUE = 22;
  public static final int IF = 4;
  public static final int CLOG = 31;
  public static final int IGUALQUE = 21;
  public static final int POR = 17;
  public static final int THENX = 12;
  public static final int TIPO = 32;
  public static final int COMA = 28;
  public static final int CST = 34;
  public static final int EOF = 0;
  public static final int DIV = 18;
  public static final int MENORQUE = 14;
  public static final int PROG = 25;
  public static final int ABRELLAVE = 26;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int INT2STR = 10;
  public static final int ASOP = 3;
  public static final int PC = 2;
  public static final int CENT = 30;
  public static final int VARS = 29;
  public static final int MAS = 15;
}

